### ISSUE TITLE
Voices problem

### ISSUE THREAD

**Issue by DarioXD2** [higurashi-mod/watanagashi#49]
I installed the patch with the ps3 BG and sprites and it worked, I also installed the voices but when I go to the game the voices sound weird, like distorted and low pitch. I already repeated the steps several times but I just cant make the voices sound right

**Comment by ItaloKnox** [comment]
Can you run the game without the voices and tell me if all the other sounds (music, effects) are working fine? This looks like a problem in your sound setup, not the game.

**Comment by DarioXD2** [comment]
I just tried it and after compare it to the other games it seems that the onikakushi and watanagashi are in some kind of slow motion making the voices and music sound weird.
The strange thing is that this only happens to chapters 1 and , 3 and 4 work just fine

**Comment by ItaloKnox** [comment]
This is the first time we see this issue and honestly I'm also at a loss here. Since the game runs on Unity, it should require at least some power or proper updates to make it run smooth, so try checking if your DirectX and display drivers are updated.

Normally I would just direct you to contact MangaGamer but I will leave this issue open so we can try to help you as much as we can. Give me a heads up if have some progress.

**Comment by DarioXD2** [comment]
Thank you, I tried updating all the drivers and windows updates and it did not work I also downloaded the original visual novel and it runs just fine.

**Comment by DarioXD2** [comment]
So, today I was going to play and I noticed the music sounded okey, I proceed to install the patch and the voices sound fine know, I really dont know how but it is fixed. Anyway thank you for the attention and support :)

**Comment by ItaloKnox** [comment]
That's awesome, if you have any trouble don't hesitate in reopening this issue!
