### ISSUE TITLE
Missing sprites

### ISSUE THREAD

**Issue by enumag** [higurashi-mod/watanagashi#50]
I didn't find any missing voices in Watanagashi. On the other hand I found a few sprites used in the scripts but missing in the graphics patch. Can we add them or replace them with other sprites that we do have?

```
night/re_si_ik_b1
night/re_si_na_b1
nigth/me_si_wa_a1
re_se_na_b1_zoom
re_se_wa_b1_zoom
```

**Comment by enumag** [comment]
@Grelo You were previously working with sprites, right? Can I ask you to look into this?

**Comment by Grelo** [comment]
@enumag np here it is....but check if everything is ok

https://mega.nz/#!tAMRBKQK!4-TRTejB38fnj33qr1XZyzls070BlujVT4tsXKBPaSc

P.S. Is it ok if i just copy them to their place in CGAlt? You said they are already in script right?
P.P.S It looks like me_si_wa_a1 sprite is in here but the path is probably messed up like your comment above **nigth** instead of **night** , good luck ;)

**Comment by enumag** [comment]
@Grelo 👍  It looks awesome. Thank you! Yeah they're in the script, just not in graphics patch. I didn't notice the typo, thanks for pointing that out. I'll fix that too. :-)

**Comment by ItaloKnox** [comment]
I'll update the graphics patch build to include these, shouldn't take too long to push the changes.

Edit: fixed and uploaded. 👍

**Comment by enumag** [comment]
Looks like there isn't much left for me to do. I fixed the typo in the script and I'll report it to the https://github.com/jwgrlrrajn/higurashi-steam-sprite-mods repository. Thank you both. 👍
