### ISSUE TITLE
MG Sprite

### ISSUE THREAD

**Issue by Grelo** [higurashi-mod/watanagashi#51]
I found MG Sprite in graphic mode so i changed it. Im not sure however if its the right one but i think it is.

![re_se_na_a2](https://cloud.githubusercontent.com/assets/22790067/25579620/ae354c76-2e79-11e7-8909-dae37bffdabc.png)

**Comment by enumag** [comment]
@Grelo Filename of the sprite?

**Comment by Grelo** [comment]
@enumag re_se_na_a2

**Comment by ItaloKnox** [comment]
Give me some light here, am I supposed to add this sprite to the graphics patch?

**Comment by enumag** [comment]
Exactly. My git still refuses to work with the graphics repo. :-(

**Comment by ItaloKnox** [comment]
The graphics repo is far from ideal, I guess the only reason why we still keep it is because my server is fast enough to work through it, heh. Anyway, all fixed!

**Comment by enumag** [comment]
The graphics repo would be completely fine if we could use Git LFS. The problem there is that GitLab doesn't resolve Git LFS when packing the zip download - the zip only contains git lfs references instead of the actual files. I've been trying to find some way to resolve these references even without git & git lfs installed but without success. :-(

**Comment by ItaloKnox** [comment]
Well, I guess that's our only option for now. Gitlab is the only service that hosts big binaries and repos, and the best thing is that it is free. If we had some source of income or anything like that, we could have our own server and solve this issue, but I don't think we reeeally need it right now. We're managing despite doing some things the hard way.
