### ISSUE TITLE
Translation Meaning

### ISSUE THREAD

**Issue by orian34** [higurashi-mod/watanagashi#78]
https://github.com/07th-mod/watanagashi/blob/abe00721d75fefbfa3efc3822467b4e0b5ac8f94/Update/wata_010.txt#L1099

This line's meaning bothers me in the context. Also, I tried to piece some kind of translation, and I think Keiichi is proposing Satoko to eat his own food, rather than him wanting to eat some. "Try me" as in eat my food too.

It felt wrong as the context clearly indicates Keiichi isn't interested in eating more, but instead is "generous" enough to give his share to Satoko(probably playing on the fact that she doesn't like pumpkin).

PS : I'll make the changes on my end if there's any to be done.

**Comment by enumag** [comment]
I can't read the japanese to verify but the translation does make sense to me.

**Comment by Norgus** [comment]
This part is translated right.

Satoko hates pumpkin but because everyone is being forcefully cheery, she's pretending to enjoy the food even though it turned out to be something she hated.

Then Keiichi gets her hopes up by suggesting he'd eat some too only to tease her by pretending to be all generous and "let her" have more of that lovely pumpkin.

**Comment by orian34** [comment]
Makes more sense, thanks for clearing my misunderstanding.
