### ISSUE TITLE
Voices only: possible missing voices

### ISSUE THREAD

**Issue by ghost** [higurashi-mod/watanagashi#95]
Got a report from a user that `in the scene . . . where you confess to Rika that you entered the shrine via the cat metaphor, and the scene in the school where everyone is sad that the mayor is missing, there was absolutely no voices. Usually it’s just a line here or there, but there it was everything`.  Not sure if intentional due to a censorship mismatch or a bug.

**Comment by enumag** [comment]
It's most likely because of PS3 differences vs orignal. The voice-only patches for early chapters in particular are certainly missing a lot of voices because any voices we added in later than the initial version (which was a significant amount for wata and tata in particular) did not make it into the voice-only version.

Any pull requests with improvements are of course highly appreciated but I don't think we'll actively work on this ourselves. Thanks for understanding.
